GET http://localhost:5000/products

###
GET http://localhost:5000/product/3

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "name": "Jam Tangan",
    "price": 150000
}

###
PATCH http://localhost:5000/product/2
Content-Type: application/json

{
    "name": "Kameja",
    "price": 100000
}

###
DELETE http://localhost:5000/product/2
